# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48e1b2927a8e771649a45845843d36f5de66dfdca2d143e9fb5ec80d9dda38240b159ade5b27c83a07b72471b2e83901e461982b109ae559918ce3633c9cebb9

test:
  secret_key_base: 76c4f5576185c7ad614eb42321df7d7f7db2763cf160d940338de0f8a0e84c401a40124e35e4c6016fb23de8c1148011057cb0f5ac7519070664a04283074bab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
